# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapyName', models.CharField(max_length=100)),
                ('therapistName', models.CharField(max_length=100)),
                ('volunteerName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ssn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='therapy',
            name='ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartSchedule.User'),
        ),
    ]
