# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='endTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='startTime',
            field=models.CharField(max_length=50),
        ),
    ]
