# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartSchedule', '0003_auto_20170504_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
